In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("reading_tablet.csv")
data

,index,name,price,number_of_comment,brand,weight(g),screen_size,comment
0,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),Máy sử dụng tốt mới dùng nên chưa đc quen lắm ...
1,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),Ship hơi lâu Rất thất vọng dịch vụ giao hàng c...
2,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),Mình đặt hàng vào ngày 71 và có hàng ngay 2 ng...
3,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),Hài lòng về máy sau 1 tuần dùng Điểm trừ giao ...
4,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),Giao hàng đúng thời gian dự kiến có 2 ngày Mì...
...,...,...,...,...,...,...,...,...
1388,24,Máy Tính Bảng Kindle Fire HD8 (8th) 16GB (2019...,2249000,165,Kindle,363.0,214 x 128 x 9.7 mm 8 inch,Cực kì hài lòng
1389,24,Máy Tính Bảng Kindle Fire HD8 (8th) 16GB (2019...,2249000,165,Kindle,363.0,214 x 128 x 9.7 mm 8 inch,máy hệ điều hành amazon nên xài dành cho nhu c...
1390,29,Máy Đọc Sách Boox Note Plus (Note+) - Hàng Nhậ...,11490000,1,BOOX,360.0,249.5 x 177.8 x 6.8 mm 10.3 inch,Dùng được hơn 5 tháng rồi có một số nhận xét n...
1391,31,Máy đọc sách Onyx Boox Note 2 - HÀNG CHÍNH HÃNG,13590000,1,Onyx Boox,NaN,NaN,Mình có mua chiếc Note 2 này từ máy đọc sách t...
1392,32,Máy Đọc Sách Likebook Muses - Hàng chính hãng,6590000,3,Likebook,NaN,193 x 136 x 8.5mm,NaN

In [3]:
review_predict = data['comment']

In [4]:
sentiment = pd.read_csv('text.csv',index_col=[0])
sentiment

      text_lb                                               text
2         1.0     Ấn tượng, tôi sẽ quay lại vào dịp nghỉ lần sau
3         1.0  Quá tuyệt vời , view đẹp , chủ nhà thân thiện ...
6         1.0  Phòng nghỉ đáng giá, tiện nghi cơ bản đầy đủ ^...
7         1.0  Thuận tiện cho việc đi thăm thú cảnh quan.\r\n...
10        1.0                               Nhân viên thân thiện
...       ...                                                ...
6994      1.0  Anh chủ rất là nhiệt tình và vui vẻ, phòng sạc...
6995      1.0  Vị trí đẹp, mặc dù chúng tôi là khách duy nhất...
6996     -1.0  Không có chỗ đỗ xe, phải gửi xe ở ngoài rất tố...
6997      1.0  Gửi quản lý cấp cao của khách sạn, Rất tiếc hì...
6998      1.0   Phòng đẹp, nhân viên cực kỳ dễ thương và chu đáo

[5199 rows x 2 columns]

In [5]:
with open('vietnamese_stopwords.txt', encoding="utf8") as f:
    stopwords = []
    for line in f:
        stopwords.append("_".join(line.strip().split()))

In [6]:
import re
from pyvi import ViTokenizer
def preprocessor(text):
    corpus = []
    for i in range(0, len(text)):
        review = re.sub(r"http\S+", "", str(text[i]))
        review = re.sub(r"#\S+", "", review)
        review = re.sub(r"@\S+", "", review)
        review = re.sub('[_]',' ',review)
        review = re.sub('[^a-zA-Z_áàạảãăắằặẵẳâấầẩậẫđíỉìịĩóòỏọõôốồổộỗơớờởợỡéèẹẽẻêếềểệễúùủũụưứừửựữýỳỷỹỵÁÀẢÃẠĂẮẰẲẲẶẴÂẤẦẬẪẨĐÍÌỈỊĨÓÒỎỌÕÔỐỒỔỘỖƠỚỜỞỢỠÉÈẺẸẼÊẾỀỆỂỄÚÙỦŨỤƯỨỪỬỰỮÝỲỶỴỸ]',
                        ' ',review)
        review = ViTokenizer.tokenize(review)
        review = review.lower()
        review = review.split()
        review = [word for word in review if not word in  set(stopwords)]
        review = ' '.join(review)
        corpus.append(review)
    return corpus

In [7]:
X = sentiment['text'].values
corpus = preprocessor(X)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer(analyzer='word', max_features=30000)
tfidf_vect.fit(corpus) 
X_data_tfidf =  tfidf_vect.transform(corpus)

from sklearn.model_selection import train_test_split
X = X_data_tfidf
y = sentiment['text_lb'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=102)

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0)
clf.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
predictions = clf.predict(X_test)
print('accuracy:',accuracy_score(y_test,predictions))

accuracy: 0.8759615384615385

In [9]:
from sklearn import svm
classifier = svm.SVC(probability=True)
classifier.fit(X_train, y_train)
train_predictions = classifier.predict(X_train)
predictions = classifier.predict(X_test)
print('accuracy:',accuracy_score(y_test,predictions))
print('confusion matrix:\n',confusion_matrix(y_test,predictions))
print('classification report:\n',classification_report(y_test,predictions))

accuracy: 0.885576923076923
confusion matrix:
 [[ 84 100]
 [ 19 837]]
classification report:
               precision    recall  f1-score   support

        -1.0       0.82      0.46      0.59       184
         1.0       0.89      0.98      0.93       856

    accuracy                           0.89      1040
   macro avg       0.85      0.72      0.76      1040
weighted avg       0.88      0.89      0.87      1040

In [10]:
X_1 = review_predict.values
corpus1 = preprocessor(X_1)
X_data_tfidf_1 =  tfidf_vect.transform(corpus1)

In [11]:
proba = classifier.predict_proba(X_data_tfidf_1)

In [12]:
df1 = pd.DataFrame(data=proba, columns=['Negative', 'Positive'])

In [13]:
data = pd.concat([data, df1], axis = 1).drop(columns = ['comment'])
data

,index,name,price,number_of_comment,brand,weight(g),screen_size,Negative,Positive
0,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.500000,0.500000
1,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.578062,0.421938
2,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.368876,0.631124
3,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.353956,0.646044
4,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.410458,0.589542
...,...,...,...,...,...,...,...,...,...
1388,24,Máy Tính Bảng Kindle Fire HD8 (8th) 16GB (2019...,2249000,165,Kindle,363.0,214 x 128 x 9.7 mm 8 inch,0.151890,0.848110
1389,24,Máy Tính Bảng Kindle Fire HD8 (8th) 16GB (2019...,2249000,165,Kindle,363.0,214 x 128 x 9.7 mm 8 inch,0.466406,0.533594
1390,29,Máy Đọc Sách Boox Note Plus (Note+) - Hàng Nhậ...,11490000,1,BOOX,360.0,249.5 x 177.8 x 6.8 mm 10.3 inch,0.228009,0.771991
1391,31,Máy đọc sách Onyx Boox Note 2 - HÀNG CHÍNH HÃNG,13590000,1,Onyx Boox,NaN,NaN,0.550537,0.449463
1392,32,Máy Đọc Sách Likebook Muses - Hàng chính hãng,6590000,3,Likebook,NaN,193 x 136 x 8.5mm,0.041301,0.958699

In [14]:
group_data = data.groupby(['index', 'name', 'price', 'number_of_comment', 'brand', 'weight(g)', 'screen_size'], as_index=False, dropna=False).mean()
#data.groupby(['index', 'name', 'price', 'number_of_comment'], as_index=False).mean()
group_data

,index,name,price,number_of_comment,brand,weight(g),screen_size,Negative,Positive
0,0,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng N...,2890000,290,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.270140,0.729860
1,1,Máy đọc sách Kindle PaperWhite Gen 4 (10th) - ...,2890000,496,Kindle,182.0,167 x 116 x 8.18 mm 6 inch,0.320837,0.679163
2,2,Máy Đọc Sách All New Kindle 2019 (10th) – Hàng...,2099000,122,Kindle,160.0,6 inch,0.295546,0.704454
3,3,Máy đọc sách Kindle PaperWhite gen 4 (10th) - ...,3550000,105,Kindle,182.0,167 x 116 x 8.18 mm 6 inch,0.373051,0.626949
4,4,Máy đọc sách All New Kindle Bản đặc biệt 8GB -...,1990000,15,Amazon,174.0,NaN,0.283719,0.716281
5,5,Combo Máy Đọc Sách Kindle Paperwhite 4 Gen 10 ...,3030000,13,Kindle,350.0,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm) 6 inch,0.212843,0.787157
6,6,Máy đọc sách Kindle Oasis 3 (2019) - Amazon - ...,6788000,18,Kindle,191.0,NaN,0.241036,0.758964
7,7,Máy tính bảng Kindle Fire HD8 Model 2020 - 32G...,2099000,10,Amazon,355.0,NaN,0.176243,0.823757
8,8,Máy đọc sách Kindle Oasis 3 - Bản Mỹ - Hàng nh...,5900000,3,Amazon,NaN,NaN,0.119644,0.880356
9,9,Máy Đọc Sách Kindle Paperwhite Gen 10 - Hàng Mỹ,2850000,20,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.330030,0.669970
10,10,Combo Máy Đọc Sách Kindle Paperwhite Gen 10th ...,3030000,15,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.315925,0.684075
11,11,Máy đọc sách Amazon Kindle Oasis 2 - dung lượn...,5650000,11,Kindle,NaN,NaN,0.265561,0.734439
12,12,Combo Máy Đọc Sách Kindle Paperwhite Gen 10th ...,3030000,6,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.201244,0.798756
13,14,Máy tính bảng Kindle Fire HD8 Plus 2020 - Ram ...,2599000,3,Amazon,355.0,NaN,0.119644,0.880356
14,15,Máy đọc sách Amazon Kindle Paperwhite 4 Gen 10...,2989000,12,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.261135,0.738865
15,17,Combo Máy Đọc Sách Kindle Paperwhite Gen 10th ...,3030000,9,Kindle,NaN,6.6” x 4.6” x 0.3” ( 167 x 116 x 8.18 mm),0.193024,0.806976
16,18,Máy Đọc Sách Kindle Gen 10 - 2019 (4GB) - Hàng...,2099000,21,Kindle,NaN,NaN,0.224421,0.775579
17,19,Máy Đọc Sách Boox Nova 2 - Hàng Chính Hãng,8790000,2,Onyx Boox,NaN,NaN,0.247510,0.752490
18,20,Máy Đọc Sách Likebook Mars - Hàng chính hãng,4990000,3,Likebook,NaN,198 x 144 x 9.3 mm,0.185432,0.814568
19,22,Máy Đọc Sách Likebook Ares - Hàng chính hãng,7490000,2,Likebook,268.0,138.7 x 198.2 x 8 mm,0.120102,0.879898
20,23,Máy Đọc Sách Kindle PaperWhite Gen 10 - 2019 (...,3850000,3,Kindle,NaN,NaN,0.360777,0.639223
21,24,Máy Tính Bảng Kindle Fire HD8 (8th) 16GB (2019...,2249000,165,Kindle,363.0,214 x 128 x 9.7 mm 8 inch,0.297097,0.702903
22,29,Máy Đọc Sách Boox Note Plus (Note+) - Hàng Nhậ...,11490000,1,BOOX,360.0,249.5 x 177.8 x 6.8 mm 10.3 inch,0.228009,0.771991
23,31,Máy đọc sách Onyx Boox Note 2 - HÀNG CHÍNH HÃNG,13590000,1,Onyx Boox,NaN,NaN,0.550537,0.449463
24,32,Máy Đọc Sách Likebook Muses - Hàng chính hãng,6590000,3,Likebook,NaN,193 x 136 x 8.5mm,0.041301,0.958699

In [15]:
rank_data = group_data.drop(columns=['index', 'name', 'brand', 'screen_size'])
rank_data.values

array([[2.89000000e+06, 2.90000000e+02,            nan, 2.70139627e-01,
        7.29860373e-01],
       [2.89000000e+06, 4.96000000e+02, 1.82000000e+02, 3.20837238e-01,
        6.79162762e-01],
       [2.09900000e+06, 1.22000000e+02, 1.60000000e+02, 2.95546468e-01,
        7.04453532e-01],
       [3.55000000e+06, 1.05000000e+02, 1.82000000e+02, 3.73050873e-01,
        6.26949127e-01],
       [1.99000000e+06, 1.50000000e+01, 1.74000000e+02, 2.83718560e-01,
        7.16281440e-01],
       [3.03000000e+06, 1.30000000e+01, 3.50000000e+02, 2.12842909e-01,
        7.87157091e-01],
       [6.78800000e+06, 1.80000000e+01, 1.91000000e+02, 2.41035622e-01,
        7.58964378e-01],
       [2.09900000e+06, 1.00000000e+01, 3.55000000e+02, 1.76243062e-01,
        8.23756938e-01],
       [5.90000000e+06, 3.00000000e+00,            nan, 1.19644277e-01,
        8.80355723e-01],
       [2.85000000e+06, 2.00000000e+01,            nan, 3.30029514e-01,
        6.69970486e-01],
       [3.03000000e+06, 1.50000000e+01,            nan, 3.15925206e-01,
        6.84074794e-01],
       [5.65000000e+06, 1.10000000e+01,            nan, 2.65561112e-01,
        7.34438888e-01],
       [3.03000000e+06, 6.00000000e+00,            nan, 2.01243662e-01,
        7.98756338e-01],
       [2.59900000e+06, 3.00000000e+00, 3.55000000e+02, 1.19644277e-01,
        8.80355723e-01],
       [2.98900000e+06, 1.20000000e+01,            nan, 2.61135176e-01,
        7.38864824e-01],
       [3.03000000e+06, 9.00000000e+00,            nan, 1.93023628e-01,
        8.06976372e-01],
       [2.09900000e+06, 2.10000000e+01,            nan, 2.24421134e-01,
        7.75578866e-01],
       [8.79000000e+06, 2.00000000e+00,            nan, 2.47509723e-01,
        7.52490277e-01],
       [4.99000000e+06, 3.00000000e+00,            nan, 1.85432019e-01,
        8.14567981e-01],
       [7.49000000e+06, 2.00000000e+00, 2.68000000e+02, 1.20102299e-01,
        8.79897701e-01],
       [3.85000000e+06, 3.00000000e+00,            nan, 3.60777433e-01,
        6.39222567e-01],
       [2.24900000e+06, 1.65000000e+02, 3.63000000e+02, 2.97097389e-01,
        7.02902611e-01],
       [1.14900000e+07, 1.00000000e+00, 3.60000000e+02, 2.28009169e-01,
        7.71990831e-01],
       [1.35900000e+07, 1.00000000e+00,            nan, 5.50537153e-01,
        4.49462847e-01],
       [6.59000000e+06, 3.00000000e+00,            nan, 4.13009067e-02,
        9.58699093e-01]])

In [16]:
pd.set_option('display.max_rows', rank_data.shape[0]+1)
rank_data[lambda col :rank_data.columns] = rank_data[lambda col :rank_data.columns].replace(r'\D+', np.NaN, regex=True)
rank_data

       price  number_of_comment  weight(g)  Negative  Positive
0    2890000                290        NaN  0.270140  0.729860
1    2890000                496      182.0  0.320837  0.679163
2    2099000                122      160.0  0.295546  0.704454
3    3550000                105      182.0  0.373051  0.626949
4    1990000                 15      174.0  0.283719  0.716281
5    3030000                 13      350.0  0.212843  0.787157
6    6788000                 18      191.0  0.241036  0.758964
7    2099000                 10      355.0  0.176243  0.823757
8    5900000                  3        NaN  0.119644  0.880356
9    2850000                 20        NaN  0.330030  0.669970
10   3030000                 15        NaN  0.315925  0.684075
11   5650000                 11        NaN  0.265561  0.734439
12   3030000                  6        NaN  0.201244  0.798756
13   2599000                  3      355.0  0.119644  0.880356
14   2989000                 12        NaN  0.261135  0.738865
15   3030000                  9        NaN  0.193024  0.806976
16   2099000                 21        NaN  0.224421  0.775579
17   8790000                  2        NaN  0.247510  0.752490
18   4990000                  3        NaN  0.185432  0.814568
19   7490000                  2      268.0  0.120102  0.879898
20   3850000                  3        NaN  0.360777  0.639223
21   2249000                165      363.0  0.297097  0.702903
22  11490000                  1      360.0  0.228009  0.771991
23  13590000                  1        NaN  0.550537  0.449463
24   6590000                  3        NaN  0.041301  0.958699

In [17]:
from sklearn.impute import KNNImputer
data_imputed = rank_data.values
ix = [i for i in range(data_imputed.shape[1]) if i != 5]
X = data_imputed[:, ix]
imputer = KNNImputer()
imputer.fit(X)
Xtrans = imputer.transform(X)
X.shape

(25, 5)

In [18]:
rank_data = pd.DataFrame(Xtrans,index=rank_data.index, columns=rank_data.columns)

In [19]:
rank_data

         price  number_of_comment  weight(g)  Negative  Positive
0    2890000.0              290.0      286.4  0.270140  0.729860
1    2890000.0              496.0      182.0  0.320837  0.679163
2    2099000.0              122.0      160.0  0.295546  0.704454
3    3550000.0              105.0      182.0  0.373051  0.626949
4    1990000.0               15.0      174.0  0.283719  0.716281
5    3030000.0               13.0      350.0  0.212843  0.787157
6    6788000.0               18.0      191.0  0.241036  0.758964
7    2099000.0               10.0      355.0  0.176243  0.823757
8    5900000.0                3.0      234.6  0.119644  0.880356
9    2850000.0               20.0      286.4  0.330030  0.669970
10   3030000.0               15.0      286.4  0.315925  0.684075
11   5650000.0               11.0      234.6  0.265561  0.734439
12   3030000.0                6.0      286.4  0.201244  0.798756
13   2599000.0                3.0      355.0  0.119644  0.880356
14   2989000.0               12.0      286.4  0.261135  0.738865
15   3030000.0                9.0      286.4  0.193024  0.806976
16   2099000.0               21.0      281.4  0.224421  0.775579
17   8790000.0                2.0      270.2  0.247510  0.752490
18   4990000.0                3.0      252.0  0.185432  0.814568
19   7490000.0                2.0      268.0  0.120102  0.879898
20   3850000.0                3.0      286.4  0.360777  0.639223
21   2249000.0              165.0      363.0  0.297097  0.702903
22  11490000.0                1.0      360.0  0.228009  0.771991
23  13590000.0                1.0      270.2  0.550537  0.449463
24   6590000.0                3.0      234.6  0.041301  0.958699

In [20]:
from sklearn.preprocessing import StandardScaler

Standard_scaler = StandardScaler()
Xtrans = Standard_scaler.fit_transform(Xtrans)

In [21]:
rank_data_scaled = pd.DataFrame(Xtrans,index=rank_data.index, columns=rank_data.columns)

In [23]:
from skcriteria import Data, MIN, MAX
ranking = Data(
    rank_data_scaled,
    [MIN, MAX, MIN, MIN, MAX],
    cnames = rank_data.columns,
    weights = [1,1,1,100,1]
)

In [24]:
from skcriteria.madm import simple
dm = simple.WeightedSum(mnorm = "sum",wnorm = "sum")
dec = dm.decide(ranking)

In [25]:
rank_data['rank'] = dec.rank_
rank_data.sort_values(by=['rank'])

         price  number_of_comment  weight(g)  Negative  Positive  rank
1    2890000.0              496.0      182.0  0.320837  0.679163     1
0    2890000.0              290.0      286.4  0.270140  0.729860     2
23  13590000.0                1.0      270.2  0.550537  0.449463     3
3    3550000.0              105.0      182.0  0.373051  0.626949     4
21   2249000.0              165.0      363.0  0.297097  0.702903     5
2    2099000.0              122.0      160.0  0.295546  0.704454     6
20   3850000.0                3.0      286.4  0.360777  0.639223     7
9    2850000.0               20.0      286.4  0.330030  0.669970     8
10   3030000.0               15.0      286.4  0.315925  0.684075     9
4    1990000.0               15.0      174.0  0.283719  0.716281    10
11   5650000.0               11.0      234.6  0.265561  0.734439    11
14   2989000.0               12.0      286.4  0.261135  0.738865    12
6    6788000.0               18.0      191.0  0.241036  0.758964    13
17   8790000.0                2.0      270.2  0.247510  0.752490    14
16   2099000.0               21.0      281.4  0.224421  0.775579    15
22  11490000.0                1.0      360.0  0.228009  0.771991    16
5    3030000.0               13.0      350.0  0.212843  0.787157    17
12   3030000.0                6.0      286.4  0.201244  0.798756    18
15   3030000.0                9.0      286.4  0.193024  0.806976    19
18   4990000.0                3.0      252.0  0.185432  0.814568    20
7    2099000.0               10.0      355.0  0.176243  0.823757    21
8    5900000.0                3.0      234.6  0.119644  0.880356    22
13   2599000.0                3.0      355.0  0.119644  0.880356    23
19   7490000.0                2.0      268.0  0.120102  0.879898    24
24   6590000.0                3.0      234.6  0.041301  0.958699    25

In [27]:
cols_to_keep = ['index', 'name', 'brand']
group_data = group_data.drop(group_data.columns.difference(cols_to_keep), axis=1)

In [28]:
pd.concat([group_data, rank_data], axis=1, join="inner").to_csv('reading_tablet_done.csv')